// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockFlow_Warehouse.Model;

#nullable disable

namespace StockFlow_Warehouse.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("StockFlow_Warehouse.Model.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("StockFlow_Warehouse.Model.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("StockFlow_Warehouse.Model.ProductAmount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WarehouseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("ProductAmount");
                });

            modelBuilder.Entity("StockFlow_Warehouse.Model.Recipient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipient");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Recipient");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("StockFlow_Warehouse.Model.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FromId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ToId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FromId");

                    b.HasIndex("ToId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("StockFlow_Warehouse.Model.Customer", b =>
                {
                    b.HasBaseType("StockFlow_Warehouse.Model.Recipient");

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("StockFlow_Warehouse.Model.Supplier", b =>
                {
                    b.HasBaseType("StockFlow_Warehouse.Model.Recipient");

                    b.HasDiscriminator().HasValue("Supplier");
                });

            modelBuilder.Entity("StockFlow_Warehouse.Model.Warehouse", b =>
                {
                    b.HasBaseType("StockFlow_Warehouse.Model.Recipient");

                    b.HasDiscriminator().HasValue("Warehouse");
                });

            modelBuilder.Entity("StockFlow_Warehouse.Model.Category", b =>
                {
                    b.HasOne("StockFlow_Warehouse.Model.Product", null)
                        .WithMany("Categories")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("StockFlow_Warehouse.Model.ProductAmount", b =>
                {
                    b.HasOne("StockFlow_Warehouse.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockFlow_Warehouse.Model.Transaction", null)
                        .WithMany("Products")
                        .HasForeignKey("TransactionId");

                    b.HasOne("StockFlow_Warehouse.Model.Warehouse", null)
                        .WithMany("Products")
                        .HasForeignKey("WarehouseId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StockFlow_Warehouse.Model.Transaction", b =>
                {
                    b.HasOne("StockFlow_Warehouse.Model.Recipient", "From")
                        .WithMany()
                        .HasForeignKey("FromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockFlow_Warehouse.Model.Recipient", "To")
                        .WithMany()
                        .HasForeignKey("ToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("From");

                    b.Navigation("To");
                });

            modelBuilder.Entity("StockFlow_Warehouse.Model.Product", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("StockFlow_Warehouse.Model.Transaction", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("StockFlow_Warehouse.Model.Warehouse", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
